# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-29 09:45
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, null=True, verbose_name='Create')),
                ('updated', django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True, null=True, verbose_name='Update')),
            ],
        ),
    ]
