# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-29 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_auto_20170329_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='visibility',
            field=models.IntegerField(choices=[(1, 'visible'), (0, 'invisible')], default=0, verbose_name='Visibility'),
        ),
    ]
