# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-21 06:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Email')),
                ('password', models.CharField(default='', max_length=100, verbose_name='Password')),
                ('firstname', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Firstname')),
                ('lastname', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Lastname')),
                ('is_vip', models.IntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], default=1, null=True, verbose_name='Is_vip ?')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Admin')),
            ],
        ),
    ]
