# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-21 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_country', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Shipping Country')),
                ('shipping_state', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Shipping State/Province')),
                ('shipping_city', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Shipping City')),
                ('shipping_address', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Shipping Address')),
                ('shipping_zip', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Shipping Zip/Postal code')),
                ('shipping_phone', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Shipping Home Phone')),
                ('shipping_mobile', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Mobile')),
                ('billing_country', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Billing Country')),
                ('billing_state', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Billing State/Province')),
                ('billing_city', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Billing City')),
                ('billing_address', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Billing Address')),
                ('billing_zip', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Billing Zip/Postal code')),
                ('billing_phone', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Billing Home Phone')),
                ('billing_mobile', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Address',
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customer'},
        ),
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer'),
        ),
    ]
