# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-21 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161221_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
