# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-28 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_is_lock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_vip',
        ),
        migrations.AddField(
            model_name='customer',
            name='discount',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='discount'),
        ),
    ]
