# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-28 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20161228_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='discount',
            field=models.FloatField(blank=True, default=1.0, help_text='From 0 to 1.0', null=True, verbose_name='discount'),
        ),
    ]
