# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-20 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170104_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Shop keeper', 'verbose_name_plural': 'Shop keeper'},
        ),
    ]
