# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-22 01:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170120_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Shop keepers', 'verbose_name_plural': 'Shop keepers'},
        ),
    ]
