# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-04 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170122_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Rate')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, null=True, verbose_name='Create')),
                ('updated', django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True, null=True, verbose_name='Update')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
    ]
