# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-07 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170206_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Account number'),
        ),
    ]
