# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-07 09:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customer_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cust_test',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer', verbose_name='cust_test'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='admin',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Admin'),
        ),
    ]
