# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-07 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20170207_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cust_test',
        ),
    ]
