# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-16 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_customer_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lock',
            field=models.IntegerField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], default=0, null=True, verbose_name='Lock ?'),
        ),
    ]
