# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-22 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20170317_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shop_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Shop name'),
        ),
    ]
