# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-24 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_address_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='default',
            field=models.BooleanField(default=True, verbose_name='Set default'),
        ),
    ]
