# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-26 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20170324_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_country', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Billing Country')),
                ('billing_state', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Billing State/Province')),
                ('billing_city', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Billing City')),
                ('billing_address', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Billing Address')),
                ('billing_zip', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Billing Zip/Postal code')),
                ('billing_phone', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Billing Home Phone')),
                ('billing_mobile', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Billing Mobile')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, null=True, verbose_name='Create')),
                ('updated', django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True, null=True, verbose_name='Update')),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer')),
            ],
            options={
                'verbose_name': 'Billing Address',
                'verbose_name_plural': 'Billing Address',
            },
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Shipping Address', 'verbose_name_plural': 'Shipping Address'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='billing_country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='billing_mobile',
        ),
        migrations.RemoveField(
            model_name='address',
            name='billing_phone',
        ),
        migrations.RemoveField(
            model_name='address',
            name='billing_state',
        ),
        migrations.RemoveField(
            model_name='address',
            name='billing_zip',
        ),
    ]
