# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-28 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20170326_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='emailed',
            field=models.BooleanField(default=True),
        ),
    ]
