# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-29 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_customer_emailed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='emailed',
            field=models.BooleanField(default=False),
        ),
    ]
