# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-05 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20170329_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='lock',
            new_name='locked',
        ),
    ]
