# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-17 16:36
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(verbose_name='\u6587\u7ae0\u5185\u5bb9')),
            ],
        ),
    ]
