# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-21 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20161221_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernum', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Ordernum')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'new'), (1, 'shipping'), (2, 'verify')], default=0, null=True, verbose_name='Order Status')),
                ('amount', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Amount')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, null=True, verbose_name='Create')),
                ('address', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Address', verbose_name='Address')),
                ('customer', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Order',
            },
        ),
    ]
