# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-21 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='', null=True, verbose_name='Message')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, null=True, verbose_name='Create')),
                ('order', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
            options={
                'verbose_name': 'OrderMessage',
                'verbose_name_plural': 'OrderMessage',
            },
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'OrderItem', 'verbose_name_plural': 'OrderItem'},
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='name',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Sku'),
        ),
    ]
