# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-21 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20161221_1412'),
        ('accounts', '0003_auto_20161221_1457'),
        ('orders', '0003_auto_20161221_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantity')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer', verbose_name='Customer')),
                ('product', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
