# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-21 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Message'),
        ),
    ]
