# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-21 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='imgorder',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Imgorder'),
        ),
    ]
