# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-23 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_imgorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermessage',
            name='quantity',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Qty'),
        ),
        migrations.AddField(
            model_name='ordermessage',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Sku'),
        ),
        migrations.AddField(
            model_name='ordermessage',
            name='tracking_link',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Track Link'),
        ),
        migrations.AddField(
            model_name='ordermessage',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Track Number'),
        ),
    ]
