# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-29 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20161223_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='order',
            name='erp_num',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='ERP_ordernum'),
        ),
    ]
