# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-29 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20161229_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Currency'),
        ),
    ]
