# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-29 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20161229_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Currency'),
        ),
    ]
