# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-29 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20161229_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_company', models.CharField(default='', max_length=200, verbose_name='Ship_company')),
                ('tracking_link', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Track Link')),
            ],
            options={
                'verbose_name': 'Shipping',
                'verbose_name_plural': 'Shipping',
            },
        ),
        migrations.RemoveField(
            model_name='ordermessage',
            name='tracking_link',
        ),
    ]
