# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-29 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20161229_0926'),
        ('orders', '0013_auto_20161229_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Sku')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('ordermessage', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='orders.OrderMessage')),
                ('product', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
