# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-29 09:20
from __future__ import unicode_literals

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_shippingitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingitem',
            name='product',
        ),
        migrations.AddField(
            model_name='shippingitem',
            name='created',
            field=django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, null=True, verbose_name='Create'),
        ),
    ]
