# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-03 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20170103_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Sku')),
                ('quantity', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Qty')),
                ('tracking_number', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Track Number')),
                ('note', models.TextField(blank=True, default='', null=True, verbose_name='Note')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, null=True, verbose_name='Create')),
                ('order', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('shipping', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='orders.Shipping', verbose_name='Shipping method')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Package',
            },
        ),
        migrations.RemoveField(
            model_name='ordermessage',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordermessage',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='shippingitem',
            name='ordermessage',
        ),
        migrations.DeleteModel(
            name='OrderMessage',
        ),
        migrations.AddField(
            model_name='shippingitem',
            name='package',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='orders.Package'),
        ),
    ]
