# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-04 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20170103_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='name',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Ref'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='stock',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Stock'),
        ),
    ]
