# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-04 09:07
from __future__ import unicode_literals

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20170104_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated',
            field=django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True, null=True, verbose_name='Update'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated',
            field=django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True, null=True, verbose_name='Update'),
        ),
        migrations.AddField(
            model_name='package',
            name='updated',
            field=django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True, null=True, verbose_name='Update'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='created',
            field=django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, null=True, verbose_name='Create'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='updated',
            field=django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True, null=True, verbose_name='Update'),
        ),
        migrations.AddField(
            model_name='shippingitem',
            name='updated',
            field=django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True, null=True, verbose_name='Update'),
        ),
    ]
