# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-05 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20170104_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_chosen',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Is_chosen'),
        ),
    ]
