# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-05 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_cartitem_is_chosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expcted_shipping',
            field=django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True, verbose_name='Expcted shipping date'),
        ),
        migrations.AddField(
            model_name='order',
            name='verifued',
            field=django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True, verbose_name='Verifued Time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Comment'),
        ),
    ]
