# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-05 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20170105_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='is_chosen',
        ),
    ]
