# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-06 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_remove_cartitem_is_chosen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='package',
            name='sku',
        ),
        migrations.AddField(
            model_name='shippingitem',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Name'),
        ),
    ]
