# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-11 03:04
from __future__ import unicode_literals

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20170106_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expcted_shipping',
            field=unixtimestampfield.fields.UnixTimeStampField(blank=True, null=True, verbose_name='Expcted shipping date'),
        ),
    ]
