# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-12 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20170112_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expcted_shipping',
            field=models.IntegerField(blank=True, null=True, verbose_name='Expcted shipping date'),
        ),
    ]
