# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-19 06:41
from __future__ import unicode_literals

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20170118_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='expected_time',
            field=django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True, verbose_name='Expected in-stock time'),
        ),
    ]
