# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-20 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_cartitem_expected_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'new'), (1, 'processing'), (2, 'partical'), (3, 'shipped'), (4, 'shipped')], default=0, null=True, verbose_name='Order Status'),
        ),
    ]
