# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-22 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20170120_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'OrderItem', 'verbose_name_plural': 'OrderItems'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
        migrations.AlterModelOptions(
            name='shipping',
            options={'verbose_name': 'Shipping', 'verbose_name_plural': 'Shippings'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'new'), (1, 'processing'), (2, 'partical shipped'), (3, 'shipped')], default=0, null=True, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='package',
            name='tracking_number',
            field=models.CharField(default='', max_length=200, verbose_name='Track Number'),
        ),
    ]
