# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-22 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_auto_20170122_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='verifued',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verifued Time'),
        ),
    ]
