# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-22 03:14
from __future__ import unicode_literals

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20170122_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='verifued',
            field=django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True, verbose_name='Verifued Time'),
        ),
    ]
