# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-03 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_auto_20170122_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'new'), (1, 'processing'), (2, 'partical shipped'), (3, 'shipped'), (4, 'cancel')], default=0, null=True, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='verifued',
            field=django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True, verbose_name='Verified Time'),
        ),
    ]
