# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-13 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20170203_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='ship_company',
            field=models.CharField(default='', max_length=200, verbose_name='Shipping Method'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='tracking_link',
            field=models.CharField(default='', max_length=200, verbose_name='Tracing Link'),
        ),
    ]
