# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-20 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_auto_20170213_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='tracking_link',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Tracing Link'),
        ),
    ]
