# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-21 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_orderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mark',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Mark'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='mark',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Mark'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='operation_type',
            field=models.CharField(default='', max_length=200, verbose_name='Operation-type'),
        ),
    ]
