# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-22 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_auto_20170321_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mark',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Stock-Mark'),
        ),
    ]
