# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-24 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_auto_20170322_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Billing Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_city',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Billing City'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_country',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Billing Country'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_mobile',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Billing Mobile'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_phone',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Billing Home Phone'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_state',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Billing State/Province'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_zip',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Billing Zip/Postal code'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Shipping Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Shipping City'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Shipping Country'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_mobile',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Mobile'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Shipping Home Phone'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_state',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Shipping State/Province'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_zip',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Shipping Zip/Postal code'),
        ),
    ]
