# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-21 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='Sku')),
                ('stock', models.IntegerField(blank=True, default=0, null=True, verbose_name='Stock')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Price')),
                ('vip_price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Vip_price')),
                ('activity_price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Activity_price')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
            },
        ),
    ]
