# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-28 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20161221_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='activity_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vip_price',
        ),
        migrations.AddField(
            model_name='product',
            name='is_net_price',
            field=models.IntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], default=0, null=True, verbose_name='Is net price ?'),
        ),
    ]
