# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-29 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20161228_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_net_price',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, verbose_name='Is net price ?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, verbose_name='Stock limit ?'),
        ),
    ]
