# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-06 03:37
from __future__ import unicode_literals

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20170103_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='created',
            field=django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, null=True, verbose_name='Create'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True, null=True, verbose_name='Update'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='created',
            field=django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, null=True, verbose_name='Create'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='updated',
            field=django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True, null=True, verbose_name='Update'),
        ),
    ]
