# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-18 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20170117_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catalog',
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(choices=[(1, 'In stock'), (2, 'Limitated stocks'), (0, 'Out of stock')], default=1, verbose_name='Stock limit'),
        ),
    ]
