# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-18 06:46
from __future__ import unicode_literals

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20170118_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expected_time',
            field=django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True, verbose_name='Expected in-stock time'),
        ),
    ]
