# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-18 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20170118_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Catalog', verbose_name='Catalog'),
        ),
    ]
