# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-18 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_catalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catalog',
        ),
    ]
