# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-20 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_catalog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name': 'Category  ', 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterField(
            model_name='product',
            name='catalog',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Catalog', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(choices=[(1, 'In stock'), (2, 'Limited stock'), (3, 'Out of stock')], default=1, verbose_name='Stock limit'),
        ),
    ]
