# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-22 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20170120_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'ProductImage', 'verbose_name_plural': 'ProductImages'},
        ),
        migrations.AddField(
            model_name='product',
            name='visibility',
            field=models.IntegerField(choices=[(1, 'visble'), (0, 'invisible')], default=1, verbose_name='Visibility'),
        ),
    ]
