# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-22 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20170122_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='visibility',
            field=models.IntegerField(choices=[(1, 'visble'), (0, 'invisible')], default=1, verbose_name='Visibility'),
        ),
    ]
