# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-03 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_productimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='discount',
            field=models.FloatField(blank=True, default=1.0, help_text='From 0 to 1.0', null=True, verbose_name='discount'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='parent',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.Catalog', verbose_name='Parent catalog'),
        ),
    ]
