# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-06 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20170203_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name': 'Category  ', 'verbose_name_plural': 'Categories'},
        ),
    ]
