# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-08 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20170206_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(choices=[(1, 'In stock'), (0, 'Out of stock')], default=1, verbose_name='Stock limit'),
        ),
    ]
