# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-13 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20170208_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(choices=[(1, 'In stock'), (0, 'Limited or Out of stock')], default=1, verbose_name='Stock limit'),
        ),
    ]
