# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-20 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20170213_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=products.models.get_product_image_upload_path, verbose_name='Image'),
        ),
    ]
