# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-16 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20170220_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock2',
            field=models.IntegerField(choices=[(1, 'In stock'), (2, 'In stock(est)'), (0, 'Limited or Out of stock')], default=1, verbose_name='CNL-Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(choices=[(1, 'In stock'), (2, 'In stock(est)'), (0, 'Limited or Out of stock')], default=1, verbose_name='Stock'),
        ),
    ]
