# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-20 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20170316_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock2',
        ),
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.IntegerField(default=0, verbose_name='Public-qty'),
        ),
        migrations.AddField(
            model_name='product',
            name='qty2',
            field=models.IntegerField(default=0, verbose_name='CNL-qty'),
        ),
    ]
