# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-05 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20170324_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_de',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description-de'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fr',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description-fr'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_nl',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description-nl'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description-en'),
        ),
    ]
