# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-17 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20170405_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='visibility',
            field=models.IntegerField(choices=[(1, 'visible'), (0, 'invisible')], default=1, verbose_name='Visibility'),
        ),
    ]
